# Generated by Django 5.1 on 2024-11-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='buyer',
        ),
        migrations.AddField(
            model_name='game',
            name='buyer',
            field=models.ManyToManyField(to='task1.buyer'),
        ),
    ]
